package cz.internetradio.app.model

data class RadioStation(
    val changeuuid: String? = null,
    val stationuuid: String? = null,
    val serveruuid: String? = null,
    val name: String,
    val url: String,
    val url_resolved: String? = null,
    val homepage: String? = null,
    val favicon: String? = null,
    val tags: String? = null,
    val country: String? = null,
    val countrycode: String? = null,
    val state: String? = null,
    val language: String? = null,
    val languagecodes: String? = null,
    val votes: Int? = null,
    val codec: String? = null,
    val bitrate: Int? = null,
    val hls: Int? = null,
    val lastcheckok: Int? = null,
    val lastchecktime: String? = null,
    val lastcheckoktime: String? = null,
    val lastchangetime: String? = null,
    val clicktimestamp: String? = null,
    val clickcount: Int? = null,
    val clicktrend: Int? = null,
    val ssl_error: Int? = null,
    val geo_lat: Double? = null,
    val geo_long: Double? = null,
    val has_extended_info: Boolean? = null,
    val isFromRadioBrowser: Boolean = false,
    var category: String? = null
) 